### ISSUE TITLE
Template Read and Write over API

### ISSUE THREAD

**Issue by pastorhudson** [mikeckennedy/listmonk#11]
Since we've already come this far are you open to a PR for Reading and Writing templates? The campaigns work, but I think I might still want to put my posts in templates instead of campaigns this way only actual sent emails are in campaigns. At least I'd like the flexibility to play with it. It seems trivial to add template support like I did campaigns. What do you think?

**Comment by mikeckennedy** [comment]
Closed via PR #10 thank you!
