### ISSUE TITLE
doesn't actually add new subscriber to list

### ISSUE THREAD

**Issue by cristianrat** [mikeckennedy/listmonk#14]
as the title says, it creates the subscriber correctly, but doesn't actually add to list
```
                new_subscriber = self.listmonk.create_subscriber(
                    email="testuser@some.domain",
                    name="Jane Doe",
                    list_ids={self.marketing_list_id},
                    pre_confirm=True,
                    attribs={"is_premium": True},
                )
```

**Comment by cristianrat** [comment]
never mind, the permissions weren't allowing access to lists
:)
surprised it doesn't throw an error, though...

**Comment by mikeckennedy** [comment]
I'm sorta surprised. However, if you interact with the API it's really crappy. The response code should have been 403 for permission denied right? Well, it was 200!

Here's the code making that call:

```python
url = f"{url_base}{urls.subscribers}"
resp = httpx.post(
    url,
    auth=(username, password),
    json=model.model_dump(),
    headers=core_headers,
    follow_redirects=True,
)
resp.raise_for_status()
```
Notice the `raise_for_status()`, that should fail on anything but 200, 201.

If you want to play around and try to detect a failure outside of the HTTP status code I'd be happy to consider a PR. Or you could hassle the Listmonk project directly to fix their API. :)
