### ISSUE TITLE
General question-  Campaign Statistics

### ISSUE THREAD

**Issue by Satishglk** [mikeckennedy/listmonk#2]
I was looking for something like this (and would love to contribute as well).  Thank you for doing this.

Is it possible to get campaign statistics via this Python package? If not, is it something that can be added?

**Comment by mikeckennedy** [comment]
Thanks @Satishglk It looks like it's possible. 

https://listmonk.app/docs/apis/campaigns/

If you're interested, use the existing methods as a model and add a few useful campaign methods. Probably get list of them, get details, and get stats.

**Comment by mikeckennedy** [comment]
Hi @Satishglk I'm going to close this issue but feel free to send a PR if it makes sense in the end.
