### ISSUE TITLE
From E-Mail should be optional when sending a transactional mail

### ISSUE THREAD

**Issue by waza-ari** [mikeckennedy/listmonk#3]
When sending a transactional mail using `send_transactional_email()`, the `from_email` is mandatory, but shouldn't be according to the [API documentation](https://listmonk.app/docs/apis/transactional/).

Ideally, this parameter is optional and is omitted in the JSON request when not presented by the user.

**Comment by mikeckennedy** [comment]
HI @waza-ari you're right that the docs do say optional. Do you know what email is used as the from if this is omitted? i.e. Why can it be optional in practice?

**Comment by waza-ari** [comment]
Hi @mikeckennedy, when not specifying the mail explicitly, it is taking the "default from mail" that can be configured on the settings page. In smaller installations (such as ours, where we really only have a single mail we're sending mails from) that is sufficient.

Its not a big deal to specify the address though and therefore not high priority I'd say.

**Comment by mikeckennedy** [comment]
Thanks Daniel. Makes sense. I just added that capability and published it as v0.1.6 on pypi.
