### ISSUE TITLE
Add ability to add attachments to transactional mails

### ISSUE THREAD

**Issue by waza-ari** [mikeckennedy/listmonk#5]
The API allows to upload and add attachments to transactional mails. I'd be willing to submit a PR adding this feature but would like to discuss if thats's a wanted addition and align on some details first.

Details can be found here: https://listmonk.app/docs/apis/transactional/

There's two changes:

1. Instead of sending the data as raw JSON, it must be sent `data` attribute in a `multipart/form-data` message.
2. The files (can be multiple files for one message) must be somehow uploaded

My proposal would be as follows:

- Extend the `send_transactional_email()` method and add an additional, optional parameter called `attachments`
- The parameter is either a list of `pathlib.Path` objects or `None`
- If `None`, the method processes as usual
- If not `None`, we verify file existence (throw an Exception if file doesn't exist). If everything looks fine, we're sending the alternative version of the request instead (multipart with files attached)

Would that be fine with you?

**Comment by mikeckennedy** [comment]
Hi @waza-ari That would be excellent. Sounds like a good plan and very useful feature for things like receipts, etc. Go for it.
